name: CI

on:
  push:
    branches: [main, develop, 'feature/*', 'hotfix/*', 'dependabot/*']
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    uses: Pursuit-Amsterdam/.github/.github/workflows/node-ci.yml@main
    with:
      node-version: '22.x'
      pnpm-version: 'latest'
      run-build: false
      run-test: false
      run-lint: true
      run-typecheck: false